name: 'IETF Publisher'
description: 'Build IETF artifacts from a base markdown (md) file.'
inputs:
  spec_filename:
    description: 'Name of the file containing the spec (in markdown format, with no extension).'
    required: true
    type: string
  spec_git_url:
    description: 'Cloneable git URL where the spec resides.'
    required: true
    type: string


runs:
  using: 'composite'
  steps:
    - run: chmod 755 $GITHUB_ACTION_PATH/build.sh
      shell: bash
    - run: chmod 755 $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/build.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/entrypoint.sh ${{ inputs.spec_git_url }} ${{ inputs.spec_filename }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: Published
        path: publication/*
